branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: swift
      env: SWIFT_SNAPSHOT=4.1.0
    - os: osx
      osx_image: xcode9
      sudo: required
      language: swift
      env: SWIFT_SNAPSHOT=4.1.0

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
after_success:
  - curl -s https://codecov.io/bash | bash

