language: swift
osx_image: xcode9.2
install:
    - gem install coveralls
before_script:
    - swift package update
script:
    - swift test    
after_success:
    - Coveralls.wear! --repo-token $coveralls_token
