language: swift
osx_image: xcode9.3
before_script:
  - swift package update
  - swift package generate-xcodeproj
script:
  - xcodebuild test -scheme FuturaAsync-Package -enableCodeCoverage YES
after_success:
  - curl -s https://codecov.io/bash | bash

