language: swift
osx_image: xcode9.2
install:
  - gem install xcov
before_script:
  - swift package update
  - swift package generate-xcodeproj
script:
  - xcodebuild test -scheme FuturaAsync-Package -enableCodeCoverage YES
after_success:
  - xcov

