language: swift
osx_image: xcode9.2
script:
    - gem install coveralls-gcov
    - swift package update
    - swift test
    - swiftcov generate --output coverage swift test 
    - coveralls-gcov send --repo-token $coveralls_token --no-gcov
