language: swift
osx_image: xcode9.2
before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
before_script:
    - swift package update
    - swift package generate-xcodeproj
script:
  - swift test
after_success: slather

